services:
  - type: web
    name: django-app
    env: python
    repo: https://github.com/tu-usuario/tu-repo.git
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn tu_proyecto.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: DEBUG
        value: "False"

databases:
  - name: django-db
    plan: free
    postgresMajorVersion: 15
