# Generated by Django 5.1.7 on 2025-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='serverities',
            field=models.CharField(default='Minor', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(default='Question', max_length=20),
        ),
    ]
