# Generated by Django 5.1.7 on 2025-05-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
