# Generated by Django 5.1.7 on 2025-05-14 10:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_status_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 5, 14), message='La fecha de vencimiento debe ser posterior a la fecha actual.')]),
        ),
    ]
