# Generated by Django 5.1.7 on 2025-03-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_issue_priority_issue_serverities_issue_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='serverities',
            new_name='serverity',
        ),
    ]
