# Generated by Django 5.1.7 on 2025-03-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_serverities_issue_serverity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='serverity',
            new_name='severity',
        ),
    ]
