# Generated by Django 5.1.7 on 2025-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='id',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
