# Generated by Django 5.1.7 on 2025-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_issue_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serverity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#808080', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#808080', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#808080', max_length=7)),
            ],
        ),
    ]
