# Generated by Django 5.1.7 on 2025-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
