# Generated by Django 5.1.7 on 2025-04-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_issue_assigned_alter_issue_created_by'),
        ('homepage', '0014_issue_deadline'),
    ]

    operations = [
    ]
