# Generated by Django 5.1.7 on 2025-04-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_watch'),
        ('homepage', '0015_merge_20250403_1831'),
    ]

    operations = [
    ]
