# Generated by Django 5.1.7 on 2025-04-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_merge_0014_watch_0015_merge_20250403_1831'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned',
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to='socialaccount.socialaccount')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.issue')),
            ],
        ),
    ]
