# Generated by Django 5.1.7 on 2025-04-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_remove_issue_assigned_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=280)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.issue')),
            ],
        ),
    ]
