# Generated by Django 5.1.7 on 2025-04-05 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_comments_created_at_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 19, 3, 59, 294815, tzinfo=datetime.timezone.utc)),
        ),
    ]
