# Generated by Django 5.1.7 on 2025-04-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_comments_created_at'),
        ('homepage', '0021_attachment'),
    ]

    operations = [
    ]
