# Generated by Django 5.1.7 on 2025-04-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_issue_created_at_issue_modified_at'),
        ('homepage', '0022_merge_0020_alter_comments_created_at_0021_attachment'),
    ]

    operations = [
    ]
