# Generated by Django 5.1.7 on 2025-04-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_comments_created_at'),
        ('homepage', '0025_userprofile'),
    ]

    operations = [
    ]
