# Generated by Django 5.1.7 on 2025-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='severity',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
