# Generated by Django 5.1.7 on 2025-04-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_userprofile'),
        ('homepage', '0026_alter_comments_created_at'),
    ]

    operations = [
    ]
