# Generated by Django 5.1.7 on 2025-04-09 22:59

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_merge_0025_userprofile_0026_alter_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.get_avatar_upload_path),
        ),
    ]
