# Generated by Django 5.1.7 on 2025-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_remove_priority_id_alter_priority_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
