# Generated by Django 5.1.7 on 2025-04-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_merge_0023_alter_comments_created_at_0025_userprofile'),
        ('homepage', '0030_remove_priority_id_alter_priority_name'),
    ]

    operations = [
    ]
