# Generated by Django 5.1.7 on 2025-04-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_userprofile_avatar'),
        ('homepage', '0031_merge_20250410_0426'),
    ]

    operations = [
    ]
