openapi: 3.0.2
info:
  version: 1.0.0
  title: Issue Tracker API
  description: API para gestionar issues en la aplicación
servers:
  - url: http://127.0.0.1:8000/
paths:
  /api/issues/:
    get:
      tags:
        - issues
      summary: Obtener todos los issues
      operationId: getAllIssues
      security:
        - ApiKeyAuth: []  
      responses:
        '200':
          description: Lista de issues obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
        '401':
          description: No autorizado

  /api/priorities/:
    get:
      summary: Obtener todas las prioridades
      security:
        - ApiKeyAuth: []  
      responses:
        '200':
          description: Lista de prioridades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Priority'
        '401':
          description: No autorizado

    post:
      summary: Crear una nueva prioridad
      security:
        - ApiKeyAuth: []  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriorityInput'
      responses:
        '201':
          description: Prioridad creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriorityInput'
        '400':
          description: Datos inválidos
        '401':
          description: No autorizado

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header  
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Error en el login"
        description:
          type: string
          example: "No se puede iniciar sesión usando Google."
        status:
          type: string
          example: "open"
        created_at:
          type: string
          
    Priority:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
          example: "#FF0000"
        position:
          type: integer
          
    PriorityInput:
      type: object
      required:
        - name
        - color
      properties:
        name:
          type: string
        color:
          type: string
          example: "#FF0000"

    