openapi: 3.0.2
info:
  version: 1.0.0
  title: Issue Tracker API
  description: API para gestionar issues en la aplicación
servers:
  - url: http://127.0.0.1:8000/
paths:
  /api/issues/:
    get:
      tags:
        - issues
      summary: Obtener todos los issues
      operationId: getAllIssues
      responses:
        '200':
          description: Lista de issues obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
        '401':
          description: No autorizado
components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Error en el login"
        description:
          type: string
          example: "No se puede iniciar sesión usando Google."
        status:
          type: string
          example: "open"
        created_at:
          type: string
          format: date-time
          example: "2025-05-07T10:23:45Z"